### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by brianamarie** [githubtraining/release-workflow#1]
Happy path works, but these are the flow and technical issues that are still outstanding. There are gates that should be added in the config, and grabbing the branch name that a user creates, but those are separate from this list. 

- [x] Should user add the pull request/issue as step 3, for the bug issue created in step 2 ? Change name of project to Release 1.0? Then, the step of creating an issue just to add to the project board may instead be a comment in the bug fix issue, and that's the issue that would be added to the project board.  023a190
- [x] Project board doesn't have columns. 4ea07b8
- [x] Have bot delete branch after merge in step 8. d6cceb4
- [x] User shouldn't close issue in step 2. Bot should do that for them, and the comment should only point them to the next issue. All important info should be in first OP or in a comment that's posted in "before" step. 3f0326f
- [x] Maybe set branch protections again before bot opens its own PR so user doesn't just merge 0d64b55
- [x] Delete outline 606ba07
